version: '3'
services:
  reverseproxy:
    image: vtran1005/reverseproxy:v1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: vtran1005/udagram-api-user:main
    environment:
      POSTGRES_USERNAME: vuitvh
      POSTGRES_PASSWORD:
      POSTGRES_DB: udagram_db
      POSTGRES_HOST: udagram-app-db.cqelv38dkdbp.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udagram-app-bucket
      JWT_SECRET: testing
      URL: 'http://localhost:8100'
  backend-feed:
    image: vtran1005/udagram-api-feed:main
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: vuitvh
      POSTGRES_PASSWORD:
      POSTGRES_DB: udagram_db
      POSTGRES_HOST: udagram-app-db.cqelv38dkdbp.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udagram-app-bucket
      JWT_SECRET: testing
      URL: 'http://localhost:8100'
  frontend:
    image: vtran1005/udagram-frontend:main
    ports:
      - '8100:80'
