version: '3'
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: vtran1005/reverseproxy:v1
  udagram-api-user:
    build:
      context: ./udagram-api-user
    image: vtran1005/udagram-api-user:main
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
    image: vtran1005/udagram-api-feed:main
  frontend:
    build:
      context: ./udagram-frontend
    image: vtran1005/udagram-frontend:main
