version: '3'
services:
  reverseproxy:
    image: vtran1005/reverseproxy:v1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - udagram-api-user
      - udagram-api-feed
    networks:
      - example-net
  udagram-api-user:
    image: vtran1005/udagram-api-user:main
    ports:
      - 8082:8082
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: 'http://localhost:8100'
    networks:
      - example-net
  udagram-api-feed:
    image: vtran1005/udagram-api-feed:main
    ports:
      - 8081:8081
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: 'http://localhost:8100'
    networks:
      - example-net
  frontend:
    image: vtran1005/udagram-frontend:main
    ports:
      - '8100:80'
    networks:
      - example-net
networks:
  example-net:
    external: true
