apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-user
  name: udagram-api-user
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: udagram-api-user
