apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-feed
  name: udagram-api-feed
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: udagram-api-feed
